---
services:
  next:
    container_name: transcendence-front-end
    image: transcendence/front-end
    build: ./
    restart: on-failure
    ports:
      - 4000:3000
    volumes:
      - ./next:/root/next
      - /root/next/node_modules
    networks:
      - docker_gaepo
    env_file:
      - ./env/.env

networks:
  docker_gaepo:
    external: true
